name: Generate Country List

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly on Sunday at midnight UTC
  workflow_dispatch:

jobs:
  generate-country-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install .; fi

      - name: Run main.py
        run: python main.py

      - name: Check for changes
        id: git-check
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add iso_country_codes.csv iso_country_codes.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git commit -m "chore: update country codes list"
          git push

      - name: Upload country codes as artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso_country_codes
          path: |
            iso_country_codes.csv
            iso_country_codes.json
