name: Generate Country List

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly on Sunday at midnight UTC
  workflow_dispatch:
  push: 
    branches:
      - main 

permissions:
  contents: write # Required to push changes to the repository
  id-token: write # Required for authentication with GitHub Actions
  actions: read # Required to use actions in the workflow


jobs:
  generate-country-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Run main.py
        run: uv run main.py

      - name: Check for changes
        id: git-check
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add iso_country_codes.csv iso_country_codes.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git commit -m "chore: update country codes list"
          git push

      - name: Upload country codes as artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso_country_codes
          path: |
            iso_country_codes.csv
            iso_country_codes.json
